version: "3.9"
services:
  localstack:
    build: ./localstack
    ports:
      - "4566:4566" # Bind LocalStack's port to localhost
    environment:
      - SERVICES=s3,transcribe
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack/volume}:/var/lib/localstack" # Mount volume for data persistence
      - "/var/run/docker.sock:/var/run/docker.sock"
